server:
  port: 9000

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DobreMihai-echo/config-server.git
          clone-on-start: true
